//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestePratico_csv
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drenagem_superficial
    {
        public string CodigoRegistro { get; set; }
        public string Atributo { get; set; }
        public string Valor { get; set; }
    }
}
